# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_auto_20170507_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='RFC',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
