# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-14 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_auto_20170413_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacion',
            name='Hist_Etapa',
            field=models.ForeignKey(blank=True, default=999, on_delete=django.db.models.deletion.CASCADE, to='comercial.Historial_Etapa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interaccion',
            name='Hist_Etapa',
            field=models.ForeignKey(blank=True, default=999, on_delete=django.db.models.deletion.CASCADE, to='comercial.Historial_Etapa'),
            preserve_default=False,
        ),
    ]
