# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_auto_20170511_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia_automotriz',
            name='URL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
