# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_auto_20170517_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia_automotriz',
            name='Grupo',
            field=models.CharField(choices=[('al', 'ALDEN'), ('an', 'ANDRADE'), ('ca', 'CAMSA'), ('ce', 'CEVER'), ('da', 'DALTON'), ('ex', 'EXCELENCIA'), ('pi', 'PICACHO'), ('so', 'SONNI'), ('ur', 'URIBE'), ('in', 'Independiente')], default='al', max_length=2),
        ),
        migrations.AlterField(
            model_name='contacto_agencia',
            name='Rol',
            field=models.CharField(choices=[('di', 'Director'), ('gv', 'Gerente de Ventas'), ('fi', 'F&I'), ('ve', 'Vendedor')], default='gv', max_length=2),
        ),
    ]
