# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-17 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_caso_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacion',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historial_etapa',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='interaccion',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
