# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-18 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_auto_20170417_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caso',
            old_name='Requiere_revision',
            new_name='Requiere_revision_admon',
        ),
        migrations.AddField(
            model_name='caso',
            name='Requiere_revision_vtas',
            field=models.BooleanField(default=False),
        ),
    ]
