# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_auto_20170530_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia_automotriz',
            name='Grupo',
            field=models.CharField(choices=[('al', 'ALDEN'), ('ae', 'AEROPLAZA'), ('an', 'ANDRADE'), ('ca', 'CAMSA'), ('ce', 'CEVER'), ('da', 'DALTON'), ('ex', 'EXCELENCIA'), ('fa', 'FAME'), ('pi', 'PICACHO'), ('ra', 'RAMSA'), ('so', 'SONNI'), ('un', 'UNIFIN'), ('ur', 'URIBE'), ('za', 'ZAPATA'), ('in', 'Independiente')], default='al', max_length=2),
        ),
    ]
