# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-05 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_auto_20170418_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia_automotriz',
            name='Grupo',
            field=models.CharField(choices=[('al', 'ALDEN'), ('ca', 'CAMSA'), ('ce', 'CEVER'), ('pi', 'PICACHO'), ('da', 'DALTON'), ('so', 'SONNI'), ('ur', 'URIBE'), ('in', 'Independiente')], default='al', max_length=2),
        ),
        migrations.AlterField(
            model_name='agencia_automotriz',
            name='Marca',
            field=models.CharField(choices=[('AC', 'ACURA'), ('AU', 'AUDI'), ('BM', 'BMW'), ('CH', 'CHEVROLET'), ('CY', 'CHRYSLER'), ('FO', 'FORD'), ('HO', 'HONDA'), ('HY', 'HYUNDAI'), ('KI', 'KIA'), ('IN', 'INFINITI'), ('IZ', 'ISUZU'), ('LN', 'LINCOLN'), ('MZ', 'MAZDA'), ('MB', 'MERCEDES BENZ'), ('NI', 'NISSAN'), ('SE', 'SEAT'), ('VW', 'VOLKSWAGEN'), ('VO', 'VOLVO')], default='FO', max_length=2),
        ),
    ]
