# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-06 22:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comercial', '0009_auto_20170505_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField()),
                ('Descripcion', models.TextField(max_length=140)),
                ('Agencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Agencia_Automotriz')),
                ('Atiende', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Cliente')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together=set([('Fecha', 'Atiende')]),
        ),
    ]
