# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-07 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_auto_20170506_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='Descripcion',
            field=models.CharField(max_length=140),
        ),
    ]
