# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-07 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0011_auto_20170507_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='Hora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='Fecha',
            field=models.DateField(),
        ),
    ]
