# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-07 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0012_auto_20170507_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
