# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-09 03:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comercial', '0013_auto_20170507_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='Descripcion',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together=set([('Fecha', 'Hora', 'Atiende')]),
        ),
    ]
