# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 15:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_Anexo', models.PositiveIntegerField()),
                ('FISO', models.CharField(max_length=20)),
                ('Fecha_Inicio', models.DateField(blank=True)),
                ('Plazo_Meses', models.PositiveIntegerField()),
                ('Monto_Anexo', models.PositiveIntegerField()),
                ('Descripcion', models.CharField(max_length=500)),
                ('Scan_Anexo', models.FileField(blank=True, null=True, upload_to=None)),
                ('Scan_Pagare', models.FileField(blank=True, null=True, upload_to=None)),
                ('Scan_Pagare_VR', models.FileField(blank=True, null=True, upload_to=None)),
                ('Scan_Carta', models.FileField(blank=True, null=True, upload_to=None)),
                ('Cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_Contrato', models.PositiveIntegerField(unique=True)),
                ('Nombre_Rep_Legal', models.CharField(max_length=100)),
                ('Nombre_Aval', models.CharField(max_length=100)),
                ('Fecha', models.DateField()),
                ('Scan_Contrato', models.FileField(blank=True, null=True, upload_to=None)),
                ('Cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Documentacion_PMoral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Creacion', models.DateField(auto_now_add=True)),
                ('Ultima_Actualizacion', models.DateField(auto_now=True)),
                ('Firma_Solicitud_Rep_legal', models.BooleanField(default=False)),
                ('Firma_Solicitud_Aval', models.BooleanField(default=False)),
                ('Edo_Fin_Anual_1', models.BooleanField(default=False)),
                ('Edo_Fin_Anual_2', models.BooleanField(default=False)),
                ('Edo_Fin_Parciales', models.BooleanField(default=False)),
                ('Declaracion_Anual_1', models.BooleanField(default=False)),
                ('Declaracion_Anual_2', models.BooleanField(default=False)),
                ('Acuse_Declaracion_1', models.BooleanField(default=False)),
                ('Acuse_Declaracion_2', models.BooleanField(default=False)),
                ('Acta_Constitutiva', models.BooleanField(default=False)),
                ('Sello_Inscripcion_Acta_Constitutiva', models.BooleanField(default=False)),
                ('Num_Notaria', models.PositiveIntegerField(blank=True, null=True)),
                ('Num_Acta_Constitutiva', models.PositiveIntegerField(blank=True, null=True)),
                ('Poderes', models.BooleanField(default=False)),
                ('Sello_Inscripcion_Poderes', models.BooleanField(default=False)),
                ('RFC', models.BooleanField(default=False)),
                ('Edo_cuenta_Rep_Legal_1', models.BooleanField(default=False)),
                ('Edo_cuenta_Rep_Legal_2', models.BooleanField(default=False)),
                ('Edo_cuenta_Rep_Legal_3', models.BooleanField(default=False)),
                ('Edo_cuenta_Aval_1', models.BooleanField(default=False)),
                ('Edo_cuenta_Aval_2', models.BooleanField(default=False)),
                ('Edo_cuenta_Aval_3', models.BooleanField(default=False)),
                ('Identificacion_Rep_legal', models.BooleanField(default=False)),
                ('Tipo_identificacion_Rep_legal', models.CharField(blank=True, choices=[('ie', 'IFE'), ('pe', 'PASAPORTE')], default='ie', max_length=2, null=True)),
                ('Num_identificacion_Rep_legal', models.CharField(blank=True, max_length=20, null=True)),
                ('Vigente_hasta_identificacion_Rep_legal', models.DateField(blank=True, null=True)),
                ('Representante_legal_es_aval', models.BooleanField(default=True)),
                ('Identificacion_Rep_Aval', models.BooleanField(default=False)),
                ('Tipo_identificacion_Aval', models.CharField(blank=True, choices=[('ie', 'IFE'), ('pe', 'PASAPORTE')], default='ie', max_length=2, null=True)),
                ('Num_identificacion_Aval', models.CharField(blank=True, max_length=20, null=True)),
                ('Vigente_hasta_identificacion_Aval', models.DateField(blank=True, null=True)),
                ('Comprobante_domicilio_Empresa', models.BooleanField(default=False)),
                ('Fuente_comprobante_domicilio_Empresa', models.CharField(blank=True, choices=[('ce', 'CFE'), ('tx', 'TELMEX'), ('ty', 'TOTAL PLAY'), ('ii', 'IZZI')], default='ce', max_length=2, null=True)),
                ('Domicilio_comprobante_domicilio_Empresa', models.CharField(blank=True, max_length=20, null=True)),
                ('Fecha_comprobante_domicilio_Empresa', models.DateField(blank=True, null=True)),
                ('Comprobante_domicilio_Aval', models.BooleanField(default=False)),
                ('Fuente_comprobante_domicilio_Aval', models.CharField(blank=True, choices=[('ce', 'CFE'), ('tx', 'TELMEX'), ('ty', 'TOTAL PLAY'), ('ii', 'IZZI')], default='ce', max_length=2, null=True)),
                ('Domicilio_comprobante_domicilio_Aval', models.CharField(blank=True, max_length=20, null=True)),
                ('Fecha_comprobante_domicilio_Aval', models.DateField(blank=True, null=True)),
                ('Aut_Buro_Empresa', models.BooleanField(default=False)),
                ('Aut_Buro_Rep_legal', models.BooleanField(default=False)),
                ('Aut_Buro_Aval', models.BooleanField(default=False)),
                ('Nota', models.CharField(blank=True, max_length=800, null=True)),
                ('Necesario_para_Evaluacion', models.BooleanField(default=False)),
                ('Caso', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Caso')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_Factura', models.PositiveIntegerField()),
                ('Monto_Factura', models.PositiveIntegerField()),
                ('Concepto_Factura', models.CharField(max_length=300)),
                ('Scan_Factura', models.FileField(blank=True, null=True, upload_to=None)),
                ('Tipo_Activo', models.CharField(choices=[('VP', 'auto particular'), ('VC', 'camion'), ('MA', 'maquinaria amarilla'), ('EC', 'equipo de computo'), ('MOB', 'mobiliario'), ('MQ', 'maquinas'), ('OT', 'otros')], default='VP', max_length=3)),
                ('Aseguradora', models.CharField(choices=[('AB', 'ABBA'), ('MA', 'MAPHRE'), ('GN', 'GNP'), ('HD', 'HDI'), ('AN', 'ANNA')], default='AB', max_length=2)),
                ('Num_Poliza', models.PositiveIntegerField()),
                ('Poliza_Fecha_Inicio', models.DateField(blank=True)),
                ('Poliza_Fecha_Final', models.DateField(blank=True)),
                ('Scan_Poliza', models.FileField(blank=True, null=True, upload_to=None)),
                ('Agencia_que_Factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Agencia_Automotriz')),
                ('Anexo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='central.Anexo')),
                ('Cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrendatario', to='comercial.Cliente')),
                ('Vendedor_Agencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Contacto_Agencia')),
            ],
        ),
        migrations.CreateModel(
            name='Modificatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion_Modificacion', models.CharField(max_length=700)),
                ('Scan_Modificatorio', models.FileField(blank=True, null=True, upload_to=None)),
                ('A_Contrato', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='central.Contrato')),
                ('Para_Anexo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='central.Anexo')),
            ],
        ),
        migrations.AddField(
            model_name='anexo',
            name='Contrato',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='central.Contrato'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='Procedente_de',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.Caso'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='Vendedor_Avance',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='factura',
            unique_together=set([('Num_Factura', 'Cliente', 'Anexo')]),
        ),
        migrations.AlterUniqueTogether(
            name='anexo',
            unique_together=set([('Num_Anexo', 'Contrato')]),
        ),
    ]
