# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poliza_Seguro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aseguradora', models.CharField(choices=[('AB', 'ABBA'), ('MA', 'MAPHRE'), ('GN', 'GNP'), ('HD', 'HDI'), ('AN', 'ANNA')], default='AB', max_length=2)),
                ('Num_Poliza', models.PositiveIntegerField()),
                ('Poliza_Fecha_Inicio', models.DateField(blank=True)),
                ('Poliza_Fecha_Final', models.DateField(blank=True)),
                ('Scan_Poliza', models.FileField(blank=True, null=True, upload_to=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='factura',
            name='Aseguradora',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='Num_Poliza',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='Poliza_Fecha_Final',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='Poliza_Fecha_Inicio',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='Scan_Poliza',
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Anotacion_Acta_Constitutiva',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Anotacion_Autorizaciones_Buro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Anotacion_Comprobantes_Domicilio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Anotacion_Declaraciones_y_Acuses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Anotacion_Edos_Cuenta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Anotacion_Edos_Fin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Anotacion_Identificaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Anotacion_RFC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Anotacion_Solicitud',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Datos_Registro',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Fecha_Acta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Fecha_Inscripcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Inscrita_en_el_Estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Inscrita_en_el_Municipio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Notario',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='Poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='central.Poliza_Seguro'),
        ),
    ]
