# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-18 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0002_auto_20170418_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacion_pmoral',
            name='Caso',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Caso'),
        ),
    ]
