# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-21 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0004_auto_20170421_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentacion_pmoral',
            name='Fecha',
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Fecha_Creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentacion_pmoral',
            name='Ultima_Actualizacion',
            field=models.DateField(auto_now=True),
        ),
    ]
