# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-12 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0005_auto_20170421_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Anotacion_Acta_Constitutiva',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Anotacion_Autorizaciones_Buro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Anotacion_Comprobantes_Domicilio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Anotacion_Declaraciones_y_Acuses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Anotacion_Edos_Cuenta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Anotacion_Edos_Fin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Anotacion_Identificaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Anotacion_RFC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Anotacion_Solicitud',
            field=models.TextField(blank=True, null=True),
        ),
    ]
