# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-15 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0006_auto_20170512_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Datos_Registro',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Fecha_Acta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Fecha_Inscripcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Inscrita_en_el_Estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Inscrita_en_el_Municipio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documentacion_pmoral',
            name='Notario',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
